xcopy /y .\Dependencies\BasicGeometryLib\bin\basicgeometrylib.dll .\Build\bin\Release\
xcopy /y .\Dependencies\OGRE\bin\OgreMain.dll .\Build\bin\Release\
xcopy /y .\Dependencies\OGRE\bin\zlib.dll .\Build\bin\Release\
xcopy /y .\Dependencies\OGRE\bin\OIS.dll .\Build\bin\Release\
xcopy /y .\Dependencies\OGRE\bin\RenderSystem_GL.dll .\Build\bin\Release\
xcopy /y .\Dependencies\Kinect2\bin\Kinect20.dll .\Build\bin\Release\
xcopy /y .\Dependencies\OGRE\config\release\plugins.cfg .\Build\bin\Release\
xcopy /y .\Dependencies\OGRE\config\ogre.cfg .\Build\bin\Release\
xcopy /y .\Dependencies\OGRE\media\Point.material .\Build\bin\Release\media\

xcopy /y .\Dependencies\BasicGeometryLib\bin\basicgeometrylib_d.dll .\Build\bin\Debug\
xcopy /y .\Dependencies\OGRE\bin\OgreMain_d.dll .\Build\bin\Debug\
xcopy /y .\Dependencies\OGRE\bin\zlib.dll .\Build\bin\Debug\
xcopy /y .\Dependencies\OGRE\bin\OIS_d.dll .\Build\bin\Debug\
xcopy /y .\Dependencies\OGRE\bin\RenderSystem_GL_d.dll .\Build\bin\Debug\
xcopy /y .\Dependencies\Kinect2\bin\Kinect20.dll .\Build\bin\Debug\
xcopy /y .\Dependencies\OGRE\config\debug\plugins_d.cfg .\Build\bin\Debug\
xcopy /y .\Dependencies\OGRE\config\ogre.cfg .\Build\bin\Debug\
xcopy /y .\Dependencies\OGRE\media\Point.material .\Build\bin\Debug\media\
